- name: Deploy containers to Docker hosts
  gather_facts: false
  hosts: all
  tasks:
    - name: Execute remote script
      script: deployment.sh
    # - name: run deploy script
    #   vyos_facts:
    #     gather_subset: all

    # - name: Display the config
    #   debug:
    #     msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"